version: '3'
services:
  phpfpm:
    build:
          context: ./
          dockerfile: Dockerfile
          args:
              env: local
              deploy_env: local
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www/html
    command: php -S="0.0.0.0:3000" -t="/var/www/html"
